import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Script } from 'node:vm';

const scriptPath = new URL('./github-home-enhancer.user.js', import.meta.url);
const source = await readFile(scriptPath, 'utf8');

assert.match(source, /@name\s+GitHub 首页增强/);
assert.match(source, /@name:en\s+GitHub Home Enhancer/);
assert.match(source, /@namespace\s+https:\/\/github\.com\/zhuxiongkai\/github-home-enhancer/);
assert.match(source, /@match\s+https:\/\/github\.com\/\*/);
assert.match(source, /@run-at\s+document-idle/);
assert.match(source, /@grant\s+none/);
assert.match(source, /@author\s+zhuxiongkai/);
assert.match(source, /@license\s+MIT/);
assert.match(source, /@homepageURL\s+https:\/\/github\.com\/zhuxiongkai\/github-home-enhancer/);
assert.match(source, /@supportURL\s+https:\/\/github\.com\/zhuxiongkai\/github-home-enhancer\/issues/);
assert.match(source, /@contributionURL\s+https:\/\/ifdian\.net\/a\/zhuxk2005/);
assert.match(source, /@updateURL\s+https:\/\/github\.com\/zhuxiongkai\/github-home-enhancer\/raw\/main\/github-home-enhancer\.user\.js/);
assert.match(source, /@downloadURL\s+https:\/\/github\.com\/zhuxiongkai\/github-home-enhancer\/raw\/main\/github-home-enhancer\.user\.js/);

assert.match(source, /gh-home-enhancer-workbench/);
assert.match(source, /const LABELS =/);
assert.match(source, /function isChineseLocale/);
assert.match(source, /document\.documentElement\.lang/);
assert.match(source, /My workspace/);
assert.match(source, /Activity/);
assert.match(source, /Related users/);
assert.match(source, /Related repositories/);
assert.match(source, /View repository/);
assert.match(source, /My activity/);
assert.match(source, /我的工作台/);
assert.match(source, /所有动态/);
assert.match(source, /我的动态/);
assert.match(source, /相关用户/);
assert.match(source, /相关仓库/);
assert.match(source, /查看仓库/);
assert.match(source, /data-feed-mode="all"/);
assert.match(source, /data-feed-mode="mine"/);
assert.match(source, /avatar/);
assert.match(source, /function githubAvatarUrl/);
assert.match(source, /githubAvatarUrl\(user\.name\)/);
assert.match(source, /--ghg-rail: 5px/);
assert.match(source, /ghg-timeline::before/);
assert.match(source, /function repoHref/);
assert.match(source, /class="ghg-event-repo"/);
assert.match(source, /ghg-user-link/);
assert.match(source, /ghg-feed-chevron/);
assert.match(source, /iconPullRequest/);
assert.match(source, /iconLock/);
assert.match(source, /timelineTemplate\(data, currentFeedMode\)/);
assert.doesNotMatch(source, /\.ghg-left-row\.is-active,\s*\.ghg-left-row:hover\s*\{\s*color:\s*#0969da/);
assert.match(source, /\.ghg-left-row:hover\s*\{[^}]*color:\s*#0969da/);
assert.match(source, /\.ghg-suggest-repo:hover\s*\{[^}]*color:\s*#0969da/);
assert.match(source, /\.ghg-links a\s*\{[^}]*color:\s*#57606a/);
assert.match(source, /\.ghg-footer a\s*\{[^}]*color:\s*#57606a/);
assert.match(source, /fetchRepoEvents/);
assert.match(source, /fetchRepoActivityItems/);
assert.match(source, /fetchRecentUserRepos/);
assert.match(source, /tab=repositories&sort=updated/);
assert.match(source, /mergeRepos/);
assert.match(source, /usersFromRepos/);
assert.match(source, /parseJsonArrayAfter/);
assert.match(source, /"activityList":\{"items":/);
assert.match(source, /\/activity/);
assert.match(source, /credentials: 'same-origin'/);
assert.match(source, /loadRealActivity/);
assert.match(source, /api\.github\.com\/repos/);
assert.match(source, /Promise\.allSettled/);
assert.match(source, /activityStatus: dashboardFeedItems\.length \? 'ready' : 'loading'/);
assert.match(source, /parseDashboardFeedItems/);
assert.match(source, /mergeFeedItems/);
assert.match(source, /ghg-skeleton-avatar/);
assert.match(source, /ghg-skeleton-line-lg/);
assert.doesNotMatch(source, /Loading real GitHub activity/);
assert.match(source, /collectGithubData/);
assert.match(source, /renderWorkbench/);
assert.match(source, /findInsertionPoint/);
assert.match(source, /feed-background/);
assert.match(source, /isLoggedInHome/);
assert.match(source, /MutationObserver/);
assert.match(source, /attributeName === 'lang'/);
assert.match(source, /setTimeout\(scheduleBoot/);
assert.match(source, /ghg-event-repo-icon/);
assert.match(source, /ghg-date-node/);
assert.match(source, /ghg-event-card/);

assert.doesNotMatch(source, /<header class="ghg-header">/);
assert.doesNotMatch(source, /ghg-brand/);
assert.doesNotMatch(source, /<strong>gitee<\/strong>/);
assert.doesNotMatch(source, /body\.\$\{ACTIVE_CLASS\} > :not/);
assert.doesNotMatch(source, />所有动态⌄<\/button>/);
assert.doesNotMatch(source, /换一批/);
assert.doesNotMatch(source, />关注<\/b>/);
assert.doesNotMatch(source, /刷新首页动态/);
assert.doesNotMatch(source, /function collectFeedItems/);
assert.doesNotMatch(source, /Repository activity synced to this workspace/);
assert.doesNotMatch(source, /Repository activity appears on this timeline/);
assert.doesNotMatch(source, /GitHub home content is organized in this timeline/);
assert.doesNotMatch(source, /index \* 7 \+ 4/);
assert.doesNotMatch(source, /repo\.private\s*\|\|\s*index\s*===\s*2/);
assert.doesNotMatch(source, /detailKey/);
assert.doesNotMatch(source, /href="https:\/\/github\.com\/organizations"/);
assert.doesNotMatch(source, /settings\/organizations/);
assert.doesNotMatch(source, /组织设置/);
assert.doesNotMatch(source, /最近参与/);
assert.doesNotMatch(source, /Git 大全/);
assert.doesNotMatch(source, /查看主页/);
assert.doesNotMatch(source, />来自 /);
assert.doesNotMatch(source, /navigator\.language/);
assert.doesNotMatch(source, /top: 64px/);
assert.doesNotMatch(source, /ghg-skeleton-date/);
assert.doesNotMatch(source, /<span><i>⌘<\/i>仓库<\/span><strong>/);
assert.doesNotMatch(source, /<strong>41<\/strong>/);
assert.doesNotMatch(source, /<strong>1<\/strong>/);
assert.doesNotMatch(source, /<strong>2<\/strong>/);
assert.doesNotMatch(source, /合并为最新版/);
assert.doesNotMatch(source, /4953 - index/);

new Script(source, { filename: 'github-home-enhancer.user.js' });

console.log('github-home-enhancer userscript contract ok');
